### ISSUE TITLE
Agoraの初期化でエラー

### ISSUE THREAD

**Issue by tsubasa1202** [tsubasa1202/withlive-android#2]
```
E/ActivityThread: Activity jp.withlive.UserLiveListActivity has leaked IntentReceiver io.agora.rtc.internal.ConnectionChangeBroadcastReceiver@3530328 that was originally registered here. Are you missing a call to unregisterReceiver()?
    android.app.IntentReceiverLeaked: Activity jp.withlive.UserLiveListActivity has leaked IntentReceiver io.agora.rtc.internal.ConnectionChangeBroadcastReceiver@3530328 that was originally registered here. Are you missing a call to unregisterReceiver()?
        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1402)
        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1140)
        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1421)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1394)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1382)
        at io.agora.rtc.internal.RtcEngineImpl.monitorConnectionEvent(RtcEngineImpl.java:544)
        at io.agora.rtc.internal.RtcEngineImpl.<init>(RtcEngineImpl.java:351)
        at io.agora.rtc.RtcEngine.create(RtcEngine.java:61)
        at jp.withlive.UserLiveListActivity.initializeAgoraEngine(UserLiveListActivity.kt:551)
        at jp.withlive.UserLiveListActivity.networkTest(UserLiveListActivity.kt:561)
        at jp.withlive.UserLiveListActivity.onCreate(UserLiveListActivity.kt:161)
        at android.app.Activity.performCreate(Activity.java:7071)
        at android.app.Activity.performCreate(Activity.java:7062)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2829)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2954)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1682)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6666)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
E/ActivityThread: Activity jp.withlive.UserLiveListActivity has leaked IntentReceiver io.agora.rtc.internal.AudioRoutingController$HeadsetBroadcastReceiver@8059d4b that was originally registered here. Are you missing a call to unregisterReceiver()?
    android.app.IntentReceiverLeaked: Activity jp.withlive.UserLiveListActivity has leaked IntentReceiver io.agora.rtc.internal.AudioRoutingController$HeadsetBroadcastReceiver@8059d4b that was originally registered here. Are you missing a call to unregisterReceiver()?
        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1402)
        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1140)
        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1421)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1394)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1382)
        at io.agora.rtc.internal.AudioRoutingController.initialize(AudioRoutingController.java:619)
        at io.agora.rtc.internal.RtcEngineImpl.<init>(RtcEngineImpl.java:347)
        at io.agora.rtc.RtcEngine.create(RtcEngine.java:61)
        at jp.withlive.UserLiveListActivity.initializeAgoraEngine(UserLiveListActivity.kt:551)
        at jp.withlive.UserLiveListActivity.networkTest(UserLiveListActivity.kt:561)
        at jp.withlive.UserLiveListActivity.onCreate(UserLiveListActivity.kt:161)
        at android.app.Activity.performCreate(Activity.java:7071)
        at android.app.Activity.performCreate(Activity.java:7062)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2829)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2954)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1682)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6666)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
I/System.out: quality: 1, inProgressNetworkTest: true
```

**Comment by tsubasa1202** [comment]
```
val handler = Handler()
```

これをthreadの中で呼び出していたの原因であった。
